### PR TITLE
Added documentation on ... arguments in BiocSingularParam classes

### PR DESCRIPTION
**Pull request by jonathangriffiths**
This may help understanding of how to use the various `Param`s - although it may be superfluous if a user pays proper attention. I'll leave that up to you to decide.

### CODE REVIEW

**Comment by LTLA** [comment]
Oh Jonny. There's no point modifying the Rd files in a Roxygen-based package.

**Comment by jonathangriffiths** [comment]
A fair point

**Comment by LTLA** [comment]
Oh fuck. I forgot that this wasn't one of my Roxygen-based packages. I take that back.

**Comment by jonathangriffiths** [comment]
In my defence, I had looked at the `R/*.R` files before diving into the `Rd`s

**Comment by LTLA** [comment]
Put in a more precise description of what is allowed in the `...`.

**Pull request closed without merging**
